const data = {
  products: [
    {
      name: 'Thermopylae chess',
      slug: 'thermopylae_chess',
      category: 'chess_games',
      image: '/images/Tchess.png',
      price: 200,
      rating: 5,
      numReviews: 104,
      countInStock: 400,
      description: 'Popular chess board with fine pieces',
    },
    {
      name: 'American Civil War chess',
      slug: 'american_civil_war_chess',
      category: 'chess_games',
      image: '/images/ACWchess.png',
      price: 70,
      rating: 3.5,
      numReviews: 15,
      countInStock: 10,
      description: 'Popular chess board with fine pieces',
    },
    {
      name: 'Templars in Crusade chess',
      slug: 'templars_chess',
      category: 'chess_games',
      image: '/images/Temchess.png',
      price: 50,
      rating: 4.5,
      numReviews: 250,
      countInStock: 100,
      description: 'Popular chess board with fine pieces',
    },
    {
      name: 'Napoleon the Waterlooser chess',
      slug: 'napoleon_chess',
      category: 'chess_games',
      image: '/images/Nchess.png',
      price: 90,
      rating: 2,
      numReviews: 44,
      countInStock: 50,
      description: 'Popular chess board with fine pieces',
    },
    {
      name: 'Grandmaster talks',
      slug: 'grandmaster_talks',
      category: 'chess_lessons',
      image: '/images/GMchess.png',
      price: 10,
      rating: 3,
      numReviews: 14,
      countInStock: '',
      description: 'Popular chess lesson with fine key spots for beginners',
    },
  ],
};

export default data;
